### ISSUE TITLE
UI changes required in custom parameter bottom sheet

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/job-manager#678]
## Current behavior
Users are confused about how to apply changes or confirm their selections within the pop-up.

## Expected behavior
1. Close button should not be present in the bottom sheet, the user should click on the backdrop to discard changes.
2. Save button should be present in the right slot of the header.
3. Copy functionality should be available for required and optional parameter groups.

## Steps to reproduce the issue
Open the Job Manager App.
Open any job.
Open custom parameter pop-up window.

## Environment details
- App version: v2.20.1
- Environment: UAT

## Additional information
![Screenshot 2024-02-16 at 12 10 07 PM](https://github.com/hotwax/job-manager/assets/158989293/1d4887e3-e1c0-4d7a-9640-97c4d60b2d96)

**Comment by ymaheshwari1** [comment]
@Adameddy26 @Dhiraj1405 I think this modal should have a close button as well, so that user have a direct option to close the modal, instead of him finding a way to the close the modal without save.

Also in case when a job is in pending state we don't allow user to make any changes in the custom parameters, so having `save` button will confuse the user about this behaviour.

**Comment by Dhiraj1405** [comment]
For the first point, I agree, that we can have a close icon. 
For the second point, let's disable the save button when the job is in a pending state.

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v2.23.1. Hence, closing this ticket.
